---
name: SFCC Deploy Action
author: Yonglong Du
description: Deploy cartridges to Salesforce Commerce Cloud sandbox or PIG
inputs:
    instance:
        description: 'instance'
        required: true
        default: '.dx.commercecloud.salesforce.com'
    client-id:
        description: 'API client id'
        required: true
        default: ''
    client-secret:
        description: 'API client secret'
        required: true
        default: ''
    code-version:
        description: 'code version'
        required: true
        default: ''
runs:
    using: node16
    main: action/index.js
