---
name: SFCC Deploy Action
author: Yonglong Du
description: Deploy cartridges to Salesforce Commerce Cloud sandbox or PIG
inputs:
    instance:
        description: 'instance'
        required: true
        default: '.dx.commercecloud.salesforce.com'
    client-id:
        description: 'API client id'
        required: true
        default: ''
    client-secret:
        description: 'API client secret'
        required: true
        default: ''
    code-version:
        description: 'code version'
        required: true
        default: ''
outputs:
    new-version:
        description: 'new version'
        value: ''
runs:
    using: 'composite'
    steps:
        - run: |
              echo $archive
              echo $src_dir
              zip $archive -r $src_dir
              ls ${{ github.workspace }}
          env:
              src_dir: ${{ github.workspace }}/cartridges
              archive: ${{ inputs.code-version }}_${{ github.run_number }}.zip
          shell: bash
